# Default Stage Setting for Development 

server:
  port: 8082

spring:
  application:
    name: routeService   
  profiles:
    active:
    - mysql
    - eureka
    - loadbalancer   
    - resilience4j
  jpa:
    defer-datasource-initialization: true # Create JPA-Schema before(!) loading SQL scripts (override new behaviour of Spring-Boot 2.5)
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop   
  
## Actuator Settings 
management:
  endpoints: 
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

## Open API Settings     
springdoc:
  api-docs:
    enabled: true
    path: /oas/v3/spec
  packagesToScan: com.thinkenterprise.route.api
  swagger-ui:
    path: /oas/v3/ui

## Instance information Settings 
route:
  service:
    version: 1
cf:
  instance:
    index: 1 
vcap:
  application:
    limits:
      mem: 512


# Product Stage Setting 

# MySQL Database Settings 
---
spring:
  config: 
    activate:
      on-profile: mysql             
  sql:
    init:
      platform: mysql
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/aircraft
    username: thinkenterprise
    password: thinkenterprise20!
    driver-class-name: com.mysql.cj.jdbc.Driver
    
# H2 Database Settings 
---
spring:
  config: 
    activate:
      on-profile: h2       
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE 
    
# Eureka Client Settings 
---
spring:
  config: 
    activate:
      on-profile: eureka
      
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5 
    registryFetchIntervalSeconds: 5
    enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

# Loadbalancer Settings 
---
spring:
  config: 
    activate:
      on-profile: loadbalancer 
  cloud:
    loadbalancer:
      retry:
        enabled: true
    

# Loadbalancer Settings 
---
spring:
  config: 
    activate:
      on-profile: resilience4j
resilience4j:
  timelimiter:
    instances:
      flightService:
        timeout-duration: 2000
 
# Test Settings
---
spring:
  config: 
    activate:
      on-profile: test  
stubrunner:
  ids-to-service-ids:
    cna-pas-springio-synchron-flight-service-final: flightService
eureka:
  client:
    enabled: false
