version: '3.8'
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=thinkenterprise20!
      - MYSQL_PASSWORD=thinkenterprise20!
      - MYSQL_USER=thinkenterprise
      - MYSQL_DATABASE=aircraft
  registry:
    image: service-registry:v1.0 
    ports:
      - 8761:8761